### PR TITLE
Implement disk managers and providers in Rust

### PR DESCRIPTION
**Pull request by AshkanAbd**
## Description

- Update providers methods.
- Implement `DiskFileManager` and `DiskDirectoryManager`.
- Add unit test for `SystemPathProvider`, `DiskFileManager` and `DiskDirectoryManager`.
- Implement `as_any` in provider.
- Rename methods and function to `async`.
- Add CHANGELOG.md.

### Related issue(s)

[#26 Implement disk managers and providers in Rust](https://github.com/EasyMicroservices/FileManager/issues/26)

### Checklist:

- [x] It refers to an [Issue](https://github.com/EasyMicroservices/FileManager/issues).
- [ ] It fixes a bug.
- [x] It's a new feature (non-breaking change which adds functionality)
- [ ] It's a breaking (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] CHANGELOG is updated.
- [ ] Related language label is selected.

### CODE REVIEW

**Comment by AshkanAbd** [comment]
It's done but I changed this PR to draft. Please fix current conflict in develop branch, I want to merge develop branch into this one.

**Comment by Ali-YousefiTelori** [comment]
@AshkanAbd Please check again.

**Comment by AshkanAbd** [comment]
@Ali-YousefiTelori @mahdidelzendeh72 
PR is ready to merge.

**Review by Ali-YousefiTelori — APPROVED** [review]
@AshkanAbd Thanks you.

**Review by mahdidelzendeh72 — APPROVED** [review]

**Pull request merged**
